apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "result-ingress"
  namespace: "default"
spec:
  defaultBackend:
    service:
      name: "result"
      port:
        number: 5001
  path: /result
  pathType: Prefix
status:
  loadBalancer: {}
